### ISSUE TITLE
get data from indeed, linkedIn, glassdoor API's

### ISSUE THREAD

**Issue by cakebatterandsprinkles** [smattern416/huntWise#11]

**Comment by Nova-Xue** [comment]
Found https://jobs.github.com/api instead of those we were going to use for they are publisher-use only and we cannot apply for a access token easily. And we found https://authenticjobs.com/api/docs as a backup api in case the github jobs will not be working.

**Comment by Nova-Xue** [comment]
Github Jobs works fine and we are using this api as main source of our data
